---
- name: install apache in redhat
  hosts: all
  become: yes

  tasks:
  - name: installing httpd package
    yum:
      name: httpd
      state: present
    notify: starting httpd

  handlers:
  - name: starting httpd
    service:
     name: httpd
     state: started

